### PR TITLE
fix script initialization order bug

### LINKED ISSUE #1327: Portal dropper broken in latest master
Pressing the "Drop portal" button doesn't do anything.

### PR DESCRIPTION
**Pull request by HifiExperiments**
fixes #1327

### CODE REVIEW

File: interface/src/Application_Setup.cpp [hunk 1]
```diff
@@ -815,8 +815,8 @@ void Application::initialize(const QCommandLineParser &parser) {
     // Needs to happen AFTER the render engine initialization to access its configuration
     initializeUi();
 
-    init();
     setupSignalsAndOperators();
```
Comment (HifiExperiments) [inline interface/src/Application_Setup.cpp:818]: `setupSignalsAndOperators` calls:
```
            scriptEngines->registerScriptInitializer([this](ScriptManagerPointer manager) {
                registerScriptEngineWithApplicationServices(manager);
            });
```

but init calls `getEntities()->init()` which sets up the script engine for all entity scripts:
```
    DependencyManager::get<ScriptEngines>()->runScriptInitializers(_nonPersistentEntitiesScriptManager);
```
so we just have to set up the signals slightly earlier.

**Review by ksuprynowicz — APPROVED** [review]
Thank you for fixing this!

**Comment by JulianGro** [comment]
Well, it fixes the portal dropper script.
