### PR TITLE
Work around transform lag in MyAvatar caused by VR keyboard

### LINKED ISSUE #2075: Severe performance regression between 2025.05 and 2025.09
MyAvatar update time increased from 0.724 to 5.208ms in tutorial. While walking or running it gets even higher, up to 9 ms.

Image

Image

### PR DESCRIPTION
**Pull request by ada-tv**
2.3ms on MyAvatar before (and now too, but only when the keyboard is raised), now 300µs when it's closed

Testable on desktop by setting `Keyboard.raised` to `true` or `false` in the JS console, you can see the MyAvatar simulation time by clicking on the stats

### CODE REVIEW

File: interface/src/ui/Keyboard.cpp [hunk 1]
```diff
@@ -378,6 +378,7 @@ void Keyboard::updateTextDisplay() {
 
 void Keyboard::raiseKeyboardAnchor(bool raise) const {
     auto entityScriptingInterface = DependencyManager::get<EntityScriptingInterface>();
+    auto myAvatar = DependencyManager::get<AvatarManager>()->getMyAvatar();
```
Comment (RTUnreal) [inline interface/src/ui/Keyboard.cpp:381]:
```suggestion
    auto* myAvatar = DependencyManager::get<AvatarManager>()->getMyAvatar();
```

Comment (ada-tv) [reply interface/src/ui/Keyboard.cpp:381]: `auto myAvatar` is how it's spelled in the rest of the file, this line was just copypasted

Comment (RTUnreal) [reply interface/src/ui/Keyboard.cpp:381]: Then let's do that another time

**Review by ksuprynowicz — APPROVED** [review]
