### PR TITLE
In-world chat bubbles and typing indicator

### LINKED ISSUE #1147: [ ArmoredChat.js ] Chat messages should show the message in 3D space near the avatar
Floating chat messages will be very useful so that people will not have to keep the chat window open to see chat messages. This will be an exceptionally great feature for users in VR because having a whole overlay open just to see chat. 

Clients should have the ability to toggle chat message visibility, which means that each user will generate the floating chat bubbles sent by other users as a local entity.

### LINKED ISSUE #1161: Typing indicator
It's a big inconvenience when we can't tell if mute (or muted) people are typing or just standing still.

Optionally, the indicator could show what is being typed live (letter by letter).

### PR DESCRIPTION
**Pull request by ada-tv**
A new setting in ArmoredChat lets the user switch between in-world bubbles or the FloofChat overlay notifications, with 3D bubbles turned on by default.

The typing indicator is always on for local and domain chat. Domain chat messages are still shown on the overlay rather than using bubbles, because they might be sent from far away.

Supports long text, clickable links, and images (if the links are on their own in a message, otherwise it'll just be a plain text message)

https://github.com/user-attachments/assets/140f0db7-9855-4e55-a795-c0bd1342aeb7

The [`chatBubbles.js`](https://raw.githubusercontent.com/ada-tv/overte/refs/heads/feature/chat-bubbles/scripts/communityScripts/chatBubbles/chatBubbles.js) script is also usable on its own with the release build to see other chat bubbles and typing indicators, though you won't send your own typing indicator events without the changes to ArmoredChat in this PR.

Closes #1147
Closes #1161

### CODE REVIEW

File: scripts/communityScripts/armored-chat/armored_chat.js [hunk 1]
```diff
@@ -160,6 +166,17 @@
...
+                if (event.setting === "worldspace_chat_bubbles") {
+                    useChatBubbles = event.value;
+                    Messages.sendLocalMessage(
+                        "ChatBubbles-Config",
+                        JSON.stringify({
+                            enabled: event.value,
+                        })
+                    );
+                    break;
+                }
```
Comment (Armored-Dragon) [inline scripts/communityScripts/armored-chat/armored_chat.js]: This is changing a new setting `useChatBubbles` instead of a setting that would be inside of the `settings` var. It may be best to change the existing var from
```javascript
    var settings = {
        external_window: false,
        maximum_messages: 200,
        join_notification: true
    };
```
to something like:
```javascript
    var settings = {
        external_window: false,
        maximum_messages: 200,
        join_notification: true,
        use_chat_bubbles: false
    };
```
This will keep it in line with the existing settings and allow you to persist the setting across sessions.

File: scripts/communityScripts/chatBubbles.js [hunk 2]
```diff
@@ -0,0 +1,333 @@
...
+
+    let link;
+
+    try {
+        const maybeURL = data.message.trim();
+
+        if (maybeURL.startsWith("https://") || maybeURL.startsWith("http://")) {
+            link = maybeURL;
+        }
+    } catch (e) {}
```
Comment (Armored-Dragon) [inline scripts/communityScripts/chatBubbles.js]: This only seems to accurately get links if the message only contains a URL. This has unexpected results if there is further text after the URL.

File: scripts/communityScripts/chatBubbles.js [hunk 3]
```diff
@@ -0,0 +1,333 @@
...
+// delete the chat bubbles and typing indicators of someone who disconnects
+AvatarList.avatarRemovedEvent.connect(sessionID => ChatBubbles_Delete(sessionID));
+AvatarList.avatarSessionChangedEvent.connect((_, oldSessionID) => ChatBubbles_Delete(oldSessionID));
+
+settings = Settings.getValue("ChatBubbles-Config", settings);
+Messages.messageReceived.connect(ChatBubbles_RecvMsg);
+Messages.subscribe(TYPING_NOTIFICATION_CHANNEL);
+
+Script.scriptEnding.connect(() => {
+	Settings.setValue("ChatBubbles-Config", settings);
```
Comment (Armored-Dragon) [inline scripts/communityScripts/chatBubbles.js]: It might be worth setting the config values when they change. It's possible the interface crashes or something else prevents the setting from being changed when the script is ending.

File: scripts/communityScripts/armored-chat/armored_chat.qml [hunk 4]
```diff
@@ -232,6 +232,13 @@ Rectangle {
                                 text = ""
                             }
                         }
+                        onTextChanged: {
+                            if (text === "") {
+                                toScript({type: "action", action: "end_typing"});
+                            } else {
+                                toScript({type: "action", action: "start_typing"});
+                            }
+                        }
```
Comment (Armored-Dragon) [inline scripts/communityScripts/armored-chat/armored_chat.qml:241]: You may be able to copy and paste this into `armored_chat_quick_message.qml` and get the same typing indicator.
Currently the quick chat window does not provide these state changes.

Comment (Armored-Dragon) [inline scripts/communityScripts/armored-chat/armored_chat.qml:241]: When typing in domain chat, the typing indicator still shows up. If this is not desired you could probably just check to see if the variable `pageVal` is equal to `domain`.

File: scripts/communityScripts/chatBubbles.js [hunk 5]
```diff
@@ -0,0 +1,333 @@
...
+		} else if (data.action === "typing_stop") {
+			ChatBubbles_HideTypingIndicator(senderID);
+		}
+	} else if (data.action === "send_chat_message" && settings.enabled) {
+        // don't spawn a bubble if they're too far away
+        if (data.channel !== "local") { return; }
+        if (Vec3.distance(MyAvatar.position, data.position) > MAX_DISTANCE) { return; }
+		ChatBubbles_SpawnBubble(data, senderID);
+    }
+}
```
Comment (Armored-Dragon) [inline scripts/communityScripts/chatBubbles.js]: Even with the setting disabled. It seems as though the typing notification will still show a indicator when another user is typing.

**Review by Armored-Dragon — CHANGES_REQUESTED** [review]
The only big issue is that when you change the chatbubble setting though the chat window, close it and re-open it, it will revert the in-world chat bubbles setting.

File: scripts/communityScripts/chatBubbles.js (hunk 5 above)
Comment (ada-tv) [reply scripts/communityScripts/chatBubbles.js]: It's intended that the typing indicator always shows. Should it be behind a separate setting?

Comment (Armored-Dragon) [reply scripts/communityScripts/chatBubbles.js]: I would imagine that if someone wanted to disable chat bubbles, the typing indicator would be disabled as well. It may be a neat idea to expand upon your typing indicator to show when someone is typing in the chat window as well. That would solve the whole 'not knowing when someone is typing' thing. As that's not a feature yet, either option of disabling the indicator with the setting or leaving it as is will be acceptable. Having it as a separate setting is probably too much at this stage.

**Review by Armored-Dragon — APPROVED** [review]
Thank you for your contribution! Everything seems to be in good shape.
Once building completes, it has my green light for merging.
