### PR TITLE
Chat bubble and simplifiedNametag fixes

### LINKED ISSUE #1672: Chat bubbles and typing indicators can clip into tall avatars

### PR DESCRIPTION
**Pull request by ada-tv**
* `simplifiedNametag` now center-aligns its text and has a thin black outline so the text appears antialiased without being transparent. It was also given `ignorePickIntersection` so it doesn't block the VR lasers.

Before
image
After
image

* The chat bubbles are are now positioned relative to the avatar's head, so the bubbles should appear at the same height above the avatar's head regardless of scale or rig shape. The bubbles are now scaled to `MyAvatar.scale` too.
* The chat bubbles now render on the `front` render layer, so they won't be occluded by ceilings or walls.
* The chat bubbles were moved up a little bit so they're mostly out of the way of the `simplifiedNametag` with an avatar scale of 1. The nametag scales itself based on its distance to the camera and isn't always the same height across different avatar scales anyway, so there might still be a bit of clashing in a few cases.

Fixes #1672

### CODE REVIEW

File: scripts/communityScripts/chatBubbles/chatBubbles.js [hunk 1]
```diff
@@ -133,30 +141,33 @@ function ChatBubbles_SpawnBubble(data, senderID) {
...
             unlit: true,
             ignorePickIntersection: (link === undefined),
-            lineHeight: BUBBLE_LINE_HEIGHT,
-            dimensions: [BUBBLE_WIDTH, height + 0.04, 0.01],
-            localPosition: [0, scale + (height / 2) + 0.1, 0],
-            backgroundAlpha: 0.5,
+            lineHeight: BUBBLE_LINE_HEIGHT * scale,
+            dimensions: Vec3.multiply(scale, [BUBBLE_WIDTH, height + 0.04, 0.01]),
+            localPosition: [0, MSG_HEAD_OFFSET_HEIGHT + headPos.y + (height / 2), 0],
+            backgroundAlpha: 0.8,
```
Comment (JulianGro) [inline scripts/communityScripts/chatBubbles/chatBubbles.js]:
```suggestion
            backgroundAlpha: 0.5,
```



With the higher opacity, the width of the chat-bubble not changing according to the text is quite a bit more annoying.
overte-snap-by-JulianGro-on-2025-08-06_10-24-53
overte-snap-by-JulianGro-on-2025-08-06_10-26-51
Maybe it would make sense to keep it more transparent until the width is dynamic?

**Review by JulianGro — APPROVED** [review]

**Review by JulianGro — APPROVED** [review]
Looks good to me. The scripting engine doesn't throw any warnings. Rendering in front seems fine as well, since the local chat already has a distance limit.
overte-snap-by--on-2025-08-11_13-05-32
