### PR TITLE
Fix getEntityProperties for group properties + keylight direction

### LINKED ISSUE #859: Keylight direction broken in latest master
The settings for keylight Vertical and horizontal angle in the create menu no longer work. It seems that the already set values still apply but changing them in create menu does nothing.
Setting it by script seems to work but it looks like getting the property returns an empty object:

```
> JSON.stringify(Entities.getEntityProperties("{b1dacebf-4811-42e3-9446-0a91fd68c0ad}", "keyLight.direction"));
< {}
```
getting a specific axis is the same:
```
> JSON.stringify(Entities.getEntityProperties("{b1dacebf-4811-42e3-9446-0a91fd68c0ad}", "keyLight.direction.x"));
< {}
```

If I do the same on current release I get all of the entity properties instead of just the direction so maybe this broke with the enterty properties PR #768 ? It is also broken on all the PR builds I have installed

Tested on win10 with master build 314.

### PR DESCRIPTION
**Pull request by HifiExperiments**
Fixes #859 

Fixes `Entities.getEntityProperties` with just a group name, and also fixes a typo `keylight.direction` -> `keyLight.direction`

### CODE REVIEW

File: libraries/entities/src/EntityItemProperties.cpp [hunk 1]
```diff
@@ -2794,7 +2794,7 @@ bool EntityItemProperties::getPropertyInfo(const QString& propertyName, EntityPr
         { // Keylight
             ADD_GROUP_PROPERTY_TO_MAP(PROP_KEYLIGHT_COLOR, KeyLight, keyLight, Color, color);
             ADD_GROUP_PROPERTY_TO_MAP(PROP_KEYLIGHT_INTENSITY, KeyLight, keyLight, Intensity, intensity);
-            ADD_GROUP_PROPERTY_TO_MAP(PROP_KEYLIGHT_DIRECTION, KeyLight, keylight, Direction, direction);
+            ADD_GROUP_PROPERTY_TO_MAP(PROP_KEYLIGHT_DIRECTION, KeyLight, keyLight, Direction, direction);
```
Comment (HifiExperiments) [inline libraries/entities/src/EntityItemProperties.cpp:2797]: lol.  lmao.

I hate how we define entity properties and it makes it SO difficult to add new ones and leads to typos like this.  I don't know how best to fix this though.  maybe we need a single file that lays out all of the entity property definitions, and using cmake or some macro hacks have it populate the necessary functions (like how we generate shader variants)?

File: libraries/entities/src/EntityItemPropertiesMacros.h [hunk 2]
```diff
@@ -459,14 +459,16 @@ inline QRect QRect_convertFromScriptValue(const ScriptValue& v, bool& isValid) {
     { \
         EntityPropertyInfo propertyInfo = EntityPropertyInfo(P); \
         _propertyInfos[#g "." #n] = propertyInfo; \
-		_enumsToPropertyStrings[P] = #g "." #n; \
+        _propertyInfos[#g].propertyEnums << P; \
```
Comment (HifiExperiments) [inline libraries/entities/src/EntityItemPropertiesMacros.h:462]: we put "keyLight.direction" in this map, but never "keyLight" (and all the multiple properties that includes).  no one ever noticed because `getEntityProperties` returned everything anyways.

File: libraries/entities/src/EntityItemProperties.cpp (hunk 1 above)
Comment (ksuprynowicz) [reply libraries/entities/src/EntityItemProperties.cpp:2797]: >  maybe we need a single file that lays out all of the entity property definitions, and using cmake or some macro hacks have it populate the necessary functions (like how we generate shader variants)?

I love that idea. Right now it's so difficult.

Comment (ksuprynowicz) [reply libraries/entities/src/EntityItemProperties.cpp:2797]: Maybe there's some schema description format or standard for such things?

**Review by ksuprynowicz — APPROVED** [review]
Everything looks fine :)

File: libraries/entities/src/EntityItemProperties.cpp (hunk 1 above)
Comment (HifiExperiments) [reply libraries/entities/src/EntityItemProperties.cpp:2797]: right now I'm thinking just a text file where each line is a property name, type, and which entity types use it...but then to support all of the other things we do, we also need to handle group properties, custom getter/setter names, maybe a way to easily specify that something is just a render property so it auto-generates the getter/setter...

**Comment by vegaslon** [comment]
Can confirm the create app works with setting the keyLight direction again as well as as being able to get the direction by script as both keyLight and keyLight.direction
