### PR TITLE
Fix stuff I broke with the VR lasers

### LINKED ISSUE #1675: VR keyboard can be very easily grabbed by accident in laser mode
Related to #1647

### LINKED ISSUE #1717: Far grab laser bugs out when clicked on the skybox
When the HUD is visible and the far grab laser is clicked on the skybox (or doesn't have anything to click on), it deactivates the far grab laser and instead turns on the HUD laser as if there was something on it. When there's nothing on the HUD, the far grab laser either goes invisible or points to (0,0,0).

Accidental regression introduced by #1695

### LINKED ISSUE #1741: Far grab lasers can't pick up local entities directly, but can pick them up when the laser is swept across them

### PR DESCRIPTION
**Pull request by ada-tv**
* Fixes #1741
* Fixes #1717
* Fixes #1675 (Supersedes the changes to the far grab scripts in #1710, in that I accidentally also started disabling the lasers when clicking directly on the keyboard)

### CODE REVIEW

File: scripts/system/controllers/controllerModules/webSurfaceLaserInput.js [hunk 1]
```diff
@@ -140,36 +140,16 @@ Script.include("/~/system/libraries/controllers.js");
             this.ignoredObjects = [];
         };
 
-        this.getInteractableType = function(controllerData, triggerPressed, checkEntitiesOnly) {
+        this.getInteractableType = function(controllerData, triggerPressed) {
             // allow pointing at tablet, unlocked web entities, or web overlays automatically without pressing trigger,
             // but for pointing at locked web entities or non-web overlays user must be pressing trigger
             var intersection = controllerData.rayPicks[this.hand];
             var objectID = intersection.objectID;
-            if (intersection.type === Picks.INTERSECTED_OVERLAY && !checkEntitiesOnly) {
```
Comment (ksuprynowicz) [inline scripts/system/controllers/controllerModules/webSurfaceLaserInput.js:148]: What was this part of code doing?

Comment (ada-tv) [reply scripts/system/controllers/controllerModules/webSurfaceLaserInput.js:148]: It checked if the laser was hitting a pre-local entities overlay to try and handle them specially. Now that overlays aren't a thing, I removed that block so it only tests against Web entities, local or not. This weird check for overlays was the cause of #1741.

**Review by ksuprynowicz — APPROVED** [review]
Everything looks good :)

**Comment by ksuprynowicz** [comment]
I tested this PR on Linux (OpenXR and Monado) and it works very well.
